name: Midseason Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 15 * *" # About 9 hours after reset (But 1-3 hours after patch)
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm install
      - name: Update
        run: npm start
      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Trackbot
          message: "chore: Midseason Update"
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

