name: Season Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *" # About 3 hours after reset
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm install
      - name: Update
        run: npm start
      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Trackbot
          message: "chore: Season Update"
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

